refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%F %H:%M:%S%.3f)} - {m}{n}"
  main:
    kind: file
    # path: /Users/suzhipeng/Business/crm-backend/log/crm-backend.log
    path: /Users/suzhipeng/Business/CRMProdEnv/backend/log/crm-backend.log
    encoder:
      pattern: "{d(%F %H:%M:%S%.3f)} - {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  main:
    level: info
    appenders:
      - main
      - stdout
    additive: false
